sudo: required

language: php

services:
  - docker

before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
- docker build -t containerum/helloworld-webhook:"$TRAVIS_COMMIT" .
- docker push containerum/helloworld-webhook:"$TRAVIS_COMMIT"

# after_success:
# -
