sudo: required

language: php

services:
  - docker

before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
- docker build -t containerum/helloworld-webhook:"$TRAVIS_COMMIT" .
- docker push containerum/helloworld-webhook:"$TRAVIS_COMMIT"

after_success:
- export GIT_SHORT_TAG=$(git rev-parse --short HEAD)
- export IMAGE="containerum/helloworld-webhook:$GIT_SHORT_TAG"
- echo $IMAGE
- |
  curl -X POST \
  https://web.api.containerum.io:5000/api/set/image/"$CONTAINERUM_WEBHOOK" \
  -H 'content-type: application/json' \
  -d '{
  "image": "$IMAGE",
  "deployment_name": "hello-webhook",
  "namespace": "mmmmm",
  "container_name": "hello-webhook"
  }'
